version: "3.3"
services:
  ce-zookeeper:
    container_name: ce-zookeeper
    image: wurstmeister/zookeeper ## 镜像
    restart: always
    ports:
      - 2182:2181
    volumes:
      - ./zookeeper/conf:/conf
      - /etc/localtime:/etc/localtime ## 挂载位置（kafka镜像和宿主机器之间时间保持一直）
    environment:
      - TZ=Asia/Shanghai
  # https://www.jianshu.com/p/1d7759d77ec1
  # https://blog.csdn.net/Crystalqy/article/details/94006936
  ce-kafka:
    container_name: ce-kafka
    image: wurstmeister/kafka ## 镜像
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 106.75.185.163 ## 修改:宿主机IP
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_ZOOKEEPER_CONNECT: ce-zookeeper:2181
      # KAFKA_ADVERTISED_PORT: 9092
      # KAFKA_LOG_RETENTION_HOURS: 120
      # KAFKA_MESSAGE_MAX_BYTES: 10000000
      # KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      # KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      # KAFKA_NUM_PARTITIONS: 3
      # KAFKA_DELETE_RETENTION_MS: 1000
    volumes:
      - ./kafka-logs:/kafka
      - /var/run/docker.sock:/var/run/docker.sock

  ce-kafka-manager:
    container_name: ce-kafka-manager
    image: sheepkiller/kafka-manager
    ports:
      - 9020:9000
    environment:
      ZK_HOSTS: zookeeper:2181
