version: "3"
services:
  ce-redis1:
    container_name: ce-redis1
    image: redis:latest
    restart: always
    ports:
      - 6380:6379
    volumes:
      - ./redis/redis1/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    # command: --requirepass "Credit2016Admin"
    networks:
      extnetwork:
  ce-redis2:
    container_name: ce-redis2
    image: redis:latest
    restart: always
    ports:
      - 6381:6379
    volumes:
      - ./redis/redis2/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    # command: --requirepass "Credit2016Admin"
    networks:
      extnetwork:
  ce-redis3:
    container_name: ce-redis3
    image: redis:latest
    restart: always
    ports:
      - 6382:6379
    volumes:
      - ./redis/redis3/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    # command: --requirepass "Credit2016Admin"
    networks:
      extnetwork:
networks:
  extnetwork:
    ipam:
      config:
        - subnet: ${subnet}
